-- MSSRP RP DAILY PAYROLL + BANK SETUP
-- Run this once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.payroll_roles (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  description text not null default '',
  monthly_salary numeric(12,2) not null default 0 check (monthly_salary >= 0),
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_payroll_roles (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  payroll_role_id uuid not null references public.payroll_roles(id) on delete restrict,
  updated_at timestamptz not null default now(),
  last_paid_on date
);

alter table public.user_payroll_roles add column if not exists last_paid_on date;

create table if not exists public.bank_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  account_number text not null unique,
  balance numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bank_transactions (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.bank_accounts(id) on delete cascade,
  amount numeric(14,2) not null,
  description text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.payroll_roles (name,description,monthly_salary,sort_order) values
('Lön1','Daglig RP-lön nivå 1',100,1),
('Lön2','Daglig RP-lön nivå 2',200,2),
('Lön3','Daglig RP-lön nivå 3',300,3),
('Lön4','Daglig RP-lön nivå 4',400,4),
('Lön5','Daglig RP-lön nivå 5',500,5),
('Lön6','Daglig RP-lön nivå 6',600,6),
('Lön7','Daglig RP-lön nivå 7',700,7),
('Lön8','Daglig RP-lön nivå 8',800,8),
('Lön9','Daglig RP-lön nivå 9',900,9),
('Lön10','Daglig RP-lön nivå 10',1000,10)
on conflict (name) do update set description=excluded.description, monthly_salary=excluded.monthly_salary, sort_order=excluded.sort_order;

create index if not exists idx_bank_transactions_account_created on public.bank_transactions(account_id, created_at desc);

-- These tables are intentionally managed by the MSSRP backend using the service role.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY to the browser.
